version: '3.1'

services:
  db:
    image: postgres
    container_name: go-rest-api-db 
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
      POSTGRES_USER: dev 
      POSTGRES_DB: dev 
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8080:8080
